"""MatAnyone 2 matting processor.

Uses a memory-based approach that requires a first-frame
segmentation mask. The mask is generated by SAM2 (see
sam2_masks.py) and fed into InferenceCore's memory before
frame processing begins.

Scene changes are detected via histogram correlation. When
a drastic change occurs (e.g. laying → standing POV), SAM2
regenerates the mask and InferenceCore's memory is reset.

Performance notes
-----------------
- ``use_fp16=True``  halves activation/weight memory (~50% VRAM).
- ``max_internal_size`` controls the resolution at which frames are
  encoded into the memory bank. 480 reduces WM tensor footprint by
  ~95% vs full-res while the decoder still outputs at full resolution
  via ResNet-50 skip connections.
- ``max_mem_frames`` caps working-memory slots before potentiation
  into long-term memory. Lower = less VRAM, slightly less temporal
  detail on fast motion.
- ``use_long_term=True`` is mandatory for videos longer than a few
  minutes — without it working memory grows without bound (OOM).
- ``compile_model=True`` traces the model with torch.compile and
  CUDA-graph-replay mode. Adds ~30 s startup cost; saves ~15-30%
  per frame afterwards. Windows requires a compatible Triton build;
  falls back gracefully if unavailable. Default False.
"""

import numpy as np
import torch
from loguru import logger

from AlphaPass.utils.gpu import configure_cuda_performance, get_device

# Re-export mask functions for backward compatibility
from AlphaPass.pipeline.sam2_masks import (  # noqa: F401
    generate_first_frame_mask,
    generate_pov_body_mask,
    _mask_center_of_mass,
    _select_non_pov_mask,
    _select_person_mask,
    _select_pov_body_mask,
)


class MatAnyone2Processor:
    """Process video frames through MatAnyone 2.

    Requires a first-frame mask (from SAM2 or manual input).
    Uses InferenceCore.step() for per-frame matting with
    recurrent memory propagation.

    In POV mode, monitors for scene changes and regenerates
    the mask via SAM2 when detected.

    Args:
        first_frame_mask: Binary mask (H, W), uint8.
        device: Target device. Auto-detected if None.
        pov_mode: Enable scene change detection for mask
            refresh. Default False.
        use_fp16: Run model weights and activations in FP16.
            Halves VRAM usage with negligible quality loss on
            CUDA devices. Ignored on CPU/MPS. Default True.
        max_internal_size: Resolution (px, short side) at which
            frames are encoded into the memory bank. -1 = full
            resolution (high VRAM). 480 is recommended for 4K+
            content. Default 480.
        max_mem_frames: Maximum working-memory key frames before
            older entries are consolidated into long-term memory.
            Lower = less VRAM. Default 3.
        use_long_term: Enable XMem-style long-term memory
            potentiation. Required for videos longer than a few
            minutes to prevent unbounded VRAM growth. Default True.
        compile_model: Apply torch.compile with CUDA-graph-replay
            mode. Reduces per-frame latency by ~15-30% after a
            one-time compilation warmup. Windows requires a
            compatible Triton build; falls back gracefully if
            unavailable. Default False.
    """

    def __init__(
        self,
        first_frame_mask: np.ndarray,
        device: torch.device | None = None,
        pov_mode: bool = False,
        *,
        use_fp16: bool = True,
        max_internal_size: int = 480,
        max_mem_frames: int = 3,
        use_long_term: bool = True,
        compile_model: bool = False,
    ):
        try:
            from matanyone2 import MatAnyone2, InferenceCore
        except ImportError:
            raise ImportError(
                "matanyone2 is required. "
                "Install with: uv sync --extra matanyone2"
            )

        if device is None:
            device = get_device()

        self.device = device
        self._mask = first_frame_mask
        self._is_first_frame = True
        self._pov_mode = pov_mode
        self._scene_detector = None
        self._use_fp16 = use_fp16 and device.type in ("cuda", "mps")

        if pov_mode:
            from AlphaPass.pipeline.scene_detect import (
                SceneChangeDetector,
            )
            self._scene_detector = SceneChangeDetector()

        # Apply global CUDA performance flags (TF32, cuDNN benchmark,
        # expandable allocator) before model weights are loaded.
        configure_cuda_performance()

        logger.info(
            f"Loading MatAnyone 2 on {device} "
            f"(fp16={self._use_fp16}, "
            f"internal_size={max_internal_size}, "
            f"mem_frames={max_mem_frames}, "
            f"long_term={use_long_term})..."
        )

        model = MatAnyone2.from_pretrained("PeiqingYang/MatAnyone2")

        # FP16: halve weight + activation memory
        if self._use_fp16:
            model = model.half()
            logger.debug("MatAnyone 2: model cast to FP16")

        # Channels-last: align conv ops with cuDNN fastest path
        if device.type == "cuda":
            model = model.to(memory_format=torch.channels_last)
            logger.debug(
                "MatAnyone 2: channels-last memory format enabled"
            )

        # torch.compile: CUDA graph replay (optional, opt-in)
        if compile_model and device.type == "cuda":
            try:
                model = torch.compile(
                    model,
                    mode="reduce-overhead",
                    dynamic=False,
                )
                logger.info(
                    "MatAnyone 2: torch.compile enabled "
                    "(first frame will be slow — compiling)"
                )
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    f"torch.compile unavailable ({exc}); "
                    "continuing without compilation"
                )

        # Apply memory tuning to the model's config before
        # passing it to InferenceCore (which reads from cfg).
        # Note: max_internal_size is NOT set here because
        # InferenceCore's internal resize is incompatible with
        # the matting path (resize expects multi-channel masks
        # but matting expects single-channel H*W). Frame
        # resolution is controlled by FrameScaler instead.
        cfg = model.cfg
        cfg.max_mem_frames = max_mem_frames
        cfg.use_long_term = use_long_term

        self._processor = InferenceCore(
            model, cfg=cfg, device=str(device)
        )
        logger.info("MatAnyone 2 loaded")

    # ── internal helpers ─────────────────────────────────────────────

    def _to_tensor(self, frame: np.ndarray) -> torch.Tensor:
        """Convert uint8 HWC numpy frame to CHW float tensor on device.

        Applies FP16 cast and channels-last layout when enabled.
        """
        t = (
            torch.from_numpy(frame)
            .float()
            .permute(2, 0, 1)
            .div(255.0)
        )
        if self._use_fp16:
            t = t.half()
        t = t.to(self.device)
        if self.device.type == "cuda":
            # channels_last requires 4-D input
            t = (
                t.unsqueeze(0)
                .to(memory_format=torch.channels_last)
                .squeeze(0)
            )
        return t

    def _autocast(self):
        """Return an autocast context manager for the active device."""
        if self._use_fp16 and self.device.type == "cuda":
            return torch.autocast(
                device_type="cuda", dtype=torch.float16
            )
        if self._use_fp16 and self.device.type == "mps":
            return torch.autocast(
                device_type="mps", dtype=torch.float16
            )
        # No-op context manager on CPU / non-FP16 paths
        return torch.autocast(device_type="cpu", enabled=False)

    def _reinit_with_mask(
        self, frame: np.ndarray, mask: np.ndarray
    ) -> np.ndarray:
        """Reinitialize memory with a new mask.

        Clears InferenceCore state and feeds the new mask,
        then predicts on the current frame.

        Returns:
            Alpha matte for the current frame.
        """
        self._mask = mask
        self._processor.clear_memory()
        self._processor.object_manager = type(
            self._processor.object_manager
        )()
        self._is_first_frame = True
        return self._process_first_frame(frame)

    def _process_first_frame(
        self, frame: np.ndarray
    ) -> np.ndarray:
        """Run the two-step first-frame initialization."""
        img_tensor = self._to_tensor(frame)

        with torch.no_grad(), self._autocast():
            mask_tensor = (
                torch.from_numpy(self._mask)
                .float()
                .to(self.device)
            )
            self._processor.step(
                img_tensor,
                mask_tensor,
                objects=[1],
            )
            output = self._processor.step(
                img_tensor,
                first_frame_pred=True,
            )

        self._is_first_frame = False
        return self._extract_matte(output)

    def _extract_matte(self, output) -> np.ndarray:
        """Convert model output to uint8 matte."""
        matte = self._processor.output_prob_to_mask(output)
        matte = (matte * 255).byte().cpu().numpy()
        if matte.ndim == 3:
            matte = matte[0]
        return matte

    # ── public API ───────────────────────────────────────────────────

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process a single frame and return the alpha matte.

        Checks for scene changes in POV mode and regenerates
        the mask if needed.

        Args:
            frame: RGB array (H, W, 3), uint8.

        Returns:
            Alpha matte (H, W), uint8 (0-255).
        """
        # Scene change detection (POV mode only)
        if (
            self._scene_detector is not None
            and not self._is_first_frame
            and self._scene_detector.check(frame)
        ):
            from AlphaPass.pipeline.sam2_masks import (
                generate_first_frame_mask,
            )
            logger.info("Scene change — regenerating MA2 mask")
            new_mask = generate_first_frame_mask(
                frame, self.device, pov_mode=True
            )
            matte = self._reinit_with_mask(frame, new_mask)
            self._scene_detector.update_reference(frame)
            return matte

        if self._is_first_frame:
            matte = self._process_first_frame(frame)
            if self._scene_detector is not None:
                self._scene_detector.update_reference(frame)
            return matte

        img_tensor = self._to_tensor(frame)

        with torch.no_grad(), self._autocast():
            output = self._processor.step(img_tensor)

        return self._extract_matte(output)

    def reset(self) -> None:
        """Reset state for a new video."""
        self._is_first_frame = True
        if self._scene_detector is not None:
            self._scene_detector.reset()

    def cleanup(self) -> None:
        """Release model and GPU memory."""
        if hasattr(self, "_processor"):
            del self._processor
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        logger.debug("MatAnyone 2 processor cleaned up")
