"""AI matte generation — protocol, factory, and wrappers.

Supports pluggable matting backends:
- RVM (Robust Video Matting): fully automatic, no first-frame mask
- MatAnyone 2: requires first-frame mask (auto-generated by SAM2)

POV mode:
- MatAnyone 2: SAM2 selects the non-POV person (quality)
- RVM: SAM2 identifies POV body, subtracted per-frame (fast/rough)

All processors implement the MatteProcessor protocol so the pipeline
runner can use them interchangeably.
"""

from typing import Protocol, runtime_checkable

import numpy as np
import torch
from loguru import logger

from vrautomatte.utils.gpu import get_device

# Valid model variant names
VARIANTS = ["mobilenetv3", "resnet50", "matanyone2"]


@runtime_checkable
class MatteProcessor(Protocol):
    """Protocol for video matting processors."""

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process a single RGB frame → alpha matte.

        Args:
            frame: RGB array (H, W, 3), uint8.

        Returns:
            Alpha matte (H, W), uint8 (0-255).
        """
        ...

    def reset(self) -> None:
        """Reset internal state between videos."""
        ...

    def cleanup(self) -> None:
        """Release GPU memory and model resources."""
        ...


class AlphaSmoother:
    """EMA temporal smoothing wrapper for any MatteProcessor.

    Blends consecutive alpha frames to reduce frame-to-frame jitter.
    alpha_out = weight * current + (1 - weight) * previous

    Args:
        inner: The actual MatteProcessor to wrap.
        weight: Blend weight for the current frame (0..1).
            1.0 = no smoothing (pass-through), lower = smoother.
    """

    def __init__(
        self,
        inner: MatteProcessor,
        weight: float = 0.85,
    ):
        self._inner = inner
        self._weight = weight
        self._prev: np.ndarray | None = None

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process frame and blend with previous matte."""
        matte = self._inner.process_frame(frame)
        if self._prev is not None:
            blended = (
                self._weight * matte.astype(np.float32)
                + (1.0 - self._weight)
                * self._prev.astype(np.float32)
            )
            matte = blended.clip(0, 255).astype(np.uint8)
        self._prev = matte.copy()
        return matte

    def reset(self) -> None:
        """Reset inner processor and smoothing state."""
        self._inner.reset()
        self._prev = None

    def cleanup(self) -> None:
        """Release inner processor resources."""
        self._inner.cleanup()
        self._prev = None


class POVExclusionProcessor:
    """Wrapper that subtracts a POV body mask from RVM output.

    SAM2 generates an initial POV body mask from frame 1.
    A scene change detector monitors for drastic changes
    (e.g. laying → standing) and regenerates the mask.

    Args:
        inner: The actual MatteProcessor (e.g. RVMProcessor).
        pov_body_mask: Binary mask (H, W), uint8 (0 or 255).
        device: GPU device for SAM2 reloads on scene change.
    """

    def __init__(
        self,
        inner: MatteProcessor,
        pov_body_mask: np.ndarray,
        device: torch.device | None = None,
    ):
        from vrautomatte.pipeline.scene_detect import (
            SceneChangeDetector,
        )

        self._inner = inner
        self._device = device or get_device()
        self._set_exclusion_mask(pov_body_mask)
        self._scene_detector = SceneChangeDetector()

    def _set_exclusion_mask(
        self, mask: np.ndarray
    ) -> None:
        """Set or update the exclusion mask."""
        self._exclusion = (
            1.0 - mask.astype(np.float32) / 255.0
        )
        logger.info(
            "POV exclusion mask set — "
            f"covers {(mask > 0).sum()} px"
        )

    def _refresh_mask(self, frame: np.ndarray) -> None:
        """Regenerate POV body mask from current frame."""
        from vrautomatte.pipeline.sam2_masks import (
            generate_pov_body_mask,
        )
        logger.info("Scene change — refreshing POV mask")
        new_mask = generate_pov_body_mask(
            frame, self._device
        )
        self._set_exclusion_mask(new_mask)
        self._scene_detector.update_reference(frame)

    def process_frame(self, frame: np.ndarray) -> np.ndarray:
        """Process frame, refresh mask on scene change."""
        if self._scene_detector.check(frame):
            self._refresh_mask(frame)

        matte = self._inner.process_frame(frame)

        # Resize exclusion mask if frame size differs
        excl = self._exclusion
        if excl.shape != matte.shape:
            from PIL import Image as _Img
            excl_img = _Img.fromarray(
                (excl * 255).astype(np.uint8), mode="L"
            ).resize(
                (matte.shape[1], matte.shape[0]),
                _Img.NEAREST,
            )
            excl = 1.0 - np.array(excl_img).astype(
                np.float32
            ) / 255.0

        result = (matte.astype(np.float32) * excl)
        return result.clip(0, 255).astype(np.uint8)

    def reset(self) -> None:
        """Reset inner processor and scene detector."""
        self._inner.reset()
        self._scene_detector.reset()

    def cleanup(self) -> None:
        """Release inner processor resources."""
        self._inner.cleanup()


def create_processor(
    variant: str,
    device: torch.device | None = None,
    downsample_ratio: float = 0.25,
    first_frame: np.ndarray | None = None,
    pov_mode: bool = False,
    *,
    use_fp16: bool = True,
    max_internal_size: int = 480,
    max_mem_frames: int = 3,
    use_long_term: bool = True,
    compile_model: bool = False,
) -> MatteProcessor:
    """Create a matting processor for the given variant.

    For matanyone2: generates SAM2 mask from first_frame,
    unloads SAM2, then loads MatAnyone 2 (D003).

    Args:
        variant: One of 'mobilenetv3', 'resnet50', 'matanyone2'.
        device: Target device. Auto-detected if None.
        downsample_ratio: RVM downscale (ignored for MA2).
        first_frame: First video frame (required for matanyone2).
        pov_mode: If True, select non-POV person mask.
        use_fp16: MatAnyone2 only — FP16 weights + activations.
        max_internal_size: MatAnyone2 only — memory encoding
            resolution (px short side). 480 recommended for 4K+.
        max_mem_frames: MatAnyone2 only — working-memory slots.
        use_long_term: MatAnyone2 only — XMem long-term memory.
        compile_model: MatAnyone2 only — torch.compile opt-in.

    Returns:
        A MatteProcessor instance.
    """
    if variant in ("mobilenetv3", "resnet50"):
        from vrautomatte.pipeline.rvm import RVMProcessor
        processor = RVMProcessor(
            variant=variant,
            downsample_ratio=downsample_ratio,
            device=device,
            use_fp16=use_fp16,
        )

        if pov_mode and first_frame is not None:
            from vrautomatte.pipeline.sam2_masks import (
                generate_pov_body_mask,
            )
            if device is None:
                device = get_device()
            logger.info(
                "RVM + POV: generating exclusion mask..."
            )
            body_mask = generate_pov_body_mask(
                first_frame, device
            )
            return POVExclusionProcessor(
                processor, body_mask, device=device
            )
        elif pov_mode:
            logger.warning(
                "POV mode requires first_frame for RVM — "
                "falling back to standard matting"
            )

        return processor

    if variant == "matanyone2":
        from vrautomatte.pipeline.matanyone2 import (
            MatAnyone2Processor,
        )
        from vrautomatte.pipeline.sam2_masks import (
            generate_first_frame_mask,
        )

        if first_frame is None:
            raise RuntimeError(
                "MatAnyone 2 requires first_frame "
                "for SAM2 mask generation"
            )

        if device is None:
            device = get_device()

        mask = generate_first_frame_mask(
            first_frame, device, pov_mode=pov_mode
        )
        return MatAnyone2Processor(
            first_frame_mask=mask,
            device=device,
            pov_mode=pov_mode,
            use_fp16=use_fp16,
            max_internal_size=max_internal_size,
            max_mem_frames=max_mem_frames,
            use_long_term=use_long_term,
            compile_model=compile_model,
        )

    raise ValueError(
        f"Unknown variant '{variant}'. Use: {VARIANTS}"
    )
